### ISSUE TITLE
Error line on my website

### ISSUE THREAD

**Issue by notepaddo** [speedyprem/disable-update-notifications#12]
Hello, I cannot use this plugin in my website https://www.spi.st/it, because it makes the following text appear on top of my pages:

Undefined array key "submit-nonce" in /home/customer/www/spi.st/public_html/it/wp-content/plugins/disable-update-notifications/index.php on line 36

The problem doesn’t happen in the english version of my website https://www.spi.st

**Comment by speedyprem** [comment]
Thanks for reporting this issue @notepaddo, I will fix this issue tomorrow and release the new version of this plugin.

**Comment by speedyprem** [comment]
@notepaddo I have fixed the warning message and update the wordpress plugin in org directory. You can now download the updated version of plugin: https://wordpress.org/plugins/disable-update-notifications/
