### ISSUE TITLE
Check boxes disappearing in wp admin

### ISSUE THREAD

**Issue by 7leafshop** [speedyprem/disable-update-notifications#7]
Checkboxes disappearing in wp-admin, 
also, radio buttons are getting css overlay..

**Comment by maxmiko** [comment]
Same thing.

**Comment by speedyprem** [comment]
Hi @7leafshop and @maxmiko 
Thanks for reporting the issue! 

This issue has been fixed in the latest version 2.3.2 https://wordpress.org/plugins/disable-update-notifications/#developers
